version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /font
  static_dir: font
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "latest"
